### ISSUE TITLE
Make Mod compat recipe load conditionally

### ISSUE THREAD

**Issue by JieningYu** [Mango-Minecraft-Project/RawOresProcessing-DataPack#1]
use Forge/Fabric load condition api in the json recipes

**Comment by EvanHsieh0415** [comment]
Do you have any suggested technical articles for reference?
I don't know how to make it because I haven't studied this kind of technology.

**Comment by JieningYu** [comment]
https://github.com/Fabricators-of-Create/Create/blob/mc1.18/fabric/dev/src/main/resources/data/create/recipes/compat/traverse/cutting/fir_log.json

https://github.com/Creators-of-Create/Create/blob/mc1.18/dev/src/generated/resources/data/create/recipes/cutting/compat/biomesoplenty/fir_log.json

**Comment by EvanHsieh0415** [comment]
Fix
[#commit-9683b70](https://github.com/EvanHsieh0415/Raw-Ores-Processing-Datapack/commit/9683b70c2f6779ef7bb94bb8c8c304a5561ba3e2)

**Comment by EvanHsieh0415** [comment]
Docs:
- Forge: https://docs.minecraftforge.net/en/1.19.x/resources/server/conditional/
- Fabric: (Still looking)
